### ISSUE TITLE
Symbol is undefined in IE11

### ISSUE THREAD

**Issue by TV5Dev** [streamroot/videojs5-hlsjs-source-handler#12]
Following error is thrown on loading of the player, quality selection and fullscreen buttons are missing:
[error] > internal error happened while processing hlsManifestLoaded:'Symbol' is undefined

Just want anyone else who has problems getting the player to load completely in IE to know that you should include the polyfills before including vjs-hls.js.

Found the solution here: http://stackoverflow.com/questions/33828840/symbol-is-undefined-in-ie-after-using-babel

Just include following before including vjs-hls.js
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser-polyfill.min.js"></script>

Regards,
TV5Dev

**Comment by AxelDelmas** [comment]
Thanks for filing this issue @TV5Dev .
From the symptom explanation, it seems to be related to https://github.com/streamroot/videojs-quality-picker which adds the quality selection menu.

@ruslandinov we should probably remove ES6 code from the quality picker, to avoid having users load babel polyfills just for this small plugin. We don't use Symbols explicitely, but babel uses it for iterator. We should remove `for ... of` loops and see if it solves the problem. Then if needed dig further in ES6 specific syntax (ES6 imports should be fine though)

**Comment by AxelDelmas** [comment]
@TV5Dev the commit above should solve your issue: you should not need babel-polyfill anymore for IE11. (Although it won't solve #11)
Can you test this new version without babel-polyfill, and confirm that you're observing the same behaviour than previous previous version with babel-polyfill?

**Comment by TV5Dev** [comment]
@AxelDelmas Thanks for fixing this. I have just rebuild latest master and confirm that it's working without any issues on IE11.
