### ISSUE TITLE
hls.js errors and more.. it works now, but what's changed?

### ISSUE THREAD

**Issue by ozette** [streamroot/videojs5-hlsjs-source-handler#25]
Up until recently I had an error in chrome, and only in _chrome_ with this lib, the hls media wouldn't play and even before the playback was started I'd receive this message:

`video.min.js:22 VIDEOJS: ERROR: (CODE:2 MEDIA_ERR_NETWORK) A network error caused the media download to fail part-way. i {code: 2, message: "A network error caused the media download to fail part-way."}`

Now I've updated to the revision of Thu Aug 11 12:47:08 2016 and hls media plays.
The media now plays as desired, but I am receiving these (harmless?) errors instead:

`HLS.js error: mediaError - fatal: false - bufferStalledError`
And sometimes (rarely) a bufferSeek error, yet the video continues to play with audio.

I found something about bufferStalledError on the github of the hls.js guys, but what's the meaning exactly of these errors, as I understand they are related to gaps or a buffer underflow?
Also, do you have any idea what changed in between this build of videojs5-hlsjs and the previous one which seems to have fixed the MEDIA_ERR_NETWORK error I had?

**Comment by ruslandinov** [comment]
Hi @ozette ,

Sorry for quite a late reply, but better late than never, right? :)

Back to your questions:
> Also, do you have any idea what changed in between this build of videojs5-hlsjs and the previous one which seems to have fixed the MEDIA_ERR_NETWORK error I had?

Most likely hls.js version updated to a new one which didn't have this problem.

> And sometimes (rarely) a bufferSeek error, yet the video continues to play with audio.
We do log errors, caught by hls.js, though not all of them are critical(`fatal` in terms of hls.js), i.e. affect playback. Here is up to date list of hls.js media errors. https://github.com/video-dev/hls.js/blob/master/docs/API.md#media-errors. Those that are not fatal are JFUI warnings, reporting playback status, like an empty buffer in case of `bufferStalledError`, which pauses the playback till hls.js gets enough data to continue the playback.

Hope this helps!
