### ISSUE TITLE
Problem with qualityPickerPlugin initialization

### ISSUE THREAD

**Issue by mkhazov** [streamroot/videojs5-hlsjs-source-handler#26]
What is the proper way to initialize a videojs-quality-picker plugin?

If I pass to videojs
```
  plugins: {
    qualityPickerPlugin: {}
  }
```
then I get the following error:
`Uncaught TypeError: Cannot read property 'on' of undefined`
on line `tech.on('loadedqualitydata', onQualityData);`
(tech is not loaded yet)

If I call `player.qualityPickerPlugin({});` after player init, the tech is loaded and `loadedqualitydata` event is already fired, so the quality picker won't appear.

**Comment by mkhazov** [comment]
I was calling `player.qualityPickerPlugin({});` in player ready callback. Calling this after player initialization did the trick.

**Comment by ellyjonez** [comment]
Thank you so much for posting this, I just ran into the same problem. Can you give an example of how you called the plugin exactly? I'm trying it a few different ways but not having any luck.

**Comment by mkhazov** [comment]
@ellyjonez 
```
const player = videojs('player-id', {
    html5: {
      hlsjsConfig: {}
    }
});
player.qualityPickerPlugin({});
```

**Comment by ellyjonez** [comment]
@mkhazov does it automatically show the quality selector button in the interface when you do this? I have it initialized now, and no errors, but no menu button in the player. thanks so much for your help - there isn't much documentation yet

**Comment by mkhazov** [comment]
@ellyjonez in my case, yes, the quality selector button is shown.
Do you pass to videojs a master playlist with several media playlists of different resolutions?

**Comment by ellyjonez** [comment]
@mkhazov yes, we have a typical master playlist setup with multiple resolutions. there is no css to include, right, just the plugin js? 🤔

one of our master playlists, for example: 

```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=379000,RESOLUTION=852x480
/projects/longer-high-res-project-for-testing/videos/23/streams/hls_235kb/segments/playlist.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1048000,RESOLUTION=852x480
/projects/longer-high-res-project-for-testing/videos/23/streams/hls_750kb/segments/playlist.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3128000,RESOLUTION=1280x720
/projects/longer-high-res-project-for-testing/videos/23/streams/hls_2350kb/segments/playlist.m3u8
```

**Comment by ellyjonez** [comment]
Got this working. Had to do this:

```
  var player = videojs('player-id');
  player.qualityPickerPlugin({})

```
