### ISSUE TITLE
Where is your npm package ?

### ISSUE THREAD

**Issue by elhampour** [streamroot/videojs5-hlsjs-source-handler#30]
this command did not work .

npm install --save videojs5-hlsjs-source-handler

**Comment by jlouazel** [comment]
Hi @elhampour,

All of our npm packages names are formatted with `streamroot-` at the beginning to avoid collisions between us and other packages.

The correct name of the package your are looking for is `streamroot-videojs5-hlsjs-p2p-source-handler`.

I hope this will help you.
