### ISSUE TITLE
How to use it with your quality picker plugin ?

### ISSUE THREAD

**Issue by elhampour** [streamroot/videojs5-hlsjs-source-handler#31]
There is not any live example , i have spent a lot of hours trying to config your plugins but i did not succeed.

i want to add a quality picker with auto and for example 360 240 p options.

**Comment by codex-corp** [comment]
@elhampour make sure to add `player.qualityPickerPlugin();`

**Comment by elhampour** [comment]
https://www.bountysource.com/issues/29963968-add-control-button-to-switch-to-a-different-hls-stream-manually

in case others encounter this problem , this is a live example i just found
