### ISSUE TITLE
What about source handler for videojs 6?

### ISSUE THREAD

**Issue by bobahvas** [streamroot/videojs5-hlsjs-source-handler#33]
VideoJs renewed [documetation](http://docs.videojs.com/) and opens by default for v6.0.0-RC.2
I think we will see 6 version soon, and also will be good have new hlsjs handler.

**Comment by jlouazel** [comment]
Hey @bobahvas,

Thanks for your interest in this module. We are closely following up releases from videojs. We will try to answer as early as possible people asking for the v6 compatibility of this module.

I'll keep you posted.

**Comment by jlouazel** [comment]
As VideoJS 6 has been officially released, I'm working on the compatibility to make it work with the latest version. You can follow the [videojs6 branch](https://github.com/streamroot/videojs5-hlsjs-source-handler/tree/videojs6) to stay up to date with the current advancements.

**Comment by fuzzynectarine** [comment]
A quick and dirty change is to change videojs.getComponent('Html5') to videojs.getTech('Html5').  I've not tested this extensively, but it is working in my local dev environment with both vjs5 and vjs6.

**Comment by jlouazel** [comment]
I will take a look. Thanks @fuzzynectarine

**Comment by ruslandinov** [comment]
Hey! This source handler is now compatible with both vjs 5 & vjs6 https://github.com/streamroot/videojs5-hlsjs-source-handler/pull/47, so I'm closing this issue.
