### ISSUE TITLE
How can i Auto Switch HLS ABR?

### ISSUE THREAD

**Issue by ravituvar** [streamroot/videojs5-hlsjs-source-handler#34]
I have a case, like I am pushing Two ABR Streams on my Server. The Stream works fine if i  keep both the streams pushing, if in case i am not pushing one stream(Specifically lower bitrate), the the player gives me error and it does not auto switch to the another stream(Higher bitrate), is there any way to handle if any one stream is not being pushed then it should autoswitch to next available stream?

**Comment by ravituvar** [comment]
Anyone can help me out on this?

**Comment by jlouazel** [comment]
Hey @ravituvar, sorry for the delay. Can you provide me more information about the error you get?

**Comment by ravituvar** [comment]
i am getting 404 on the Lower stream, as the stream is not being pushed, but the player should auto switch to Higher bandwidth stream or next available stream if any stream is not found in ABR case..

**Comment by jlouazel** [comment]
Seems related to hls.js (https://github.com/video-dev/hls.js/issues/573). We gonna switch to **hls.js@0.6.21** in the next few days which seems to solve this issue.

I'm closing this issue as this is not directly related to this repository, you can follow #35 to stay tuned on the move we gonna take.
