### ISSUE TITLE
Do you plan to update hls.js version to the latest?

### ISSUE THREAD

**Issue by mahmutbayri** [streamroot/videojs5-hlsjs-source-handler#35]
The latest version of hls.js is v0.7.4, videojs5-hlsjs-source-handler uses its v0.5.5.

**Comment by jlouazel** [comment]
Hey @mahmutbayri,

We are currently looking deeply into **hls.js@0.7.4** to  avoid compatibility issues. It should be done in the next few days if everything goes well.

**Comment by ruslandinov** [comment]
Done :) https://github.com/streamroot/videojs5-hlsjs-source-handler/blob/master/package.json#L18
