### ISSUE TITLE
Is it possible to set default quality?

### ISSUE THREAD

**Issue by morkov4o** [streamroot/videojs5-hlsjs-source-handler#39]
Default is "auto" quality and if we have a small player it does not make sense to force big files. 
Is it possible to force 360p for example on load ?

**Comment by ruslandinov** [comment]
Hello @morkov4o 
Yes, that's possible. Set `startLevel` hls.js config param(https://github.com/video-dev/hls.js/blob/master/doc/API.md#startlevel) to a value that suits you, and pass this param in `hlsjsConfig` as described here https://github.com/streamroot/videojs5-hlsjs-source-handler#passing-configuration-options-to-hlsjs

**Comment by morkov4o** [comment]
Hi @ruslandinov, 
thanks for your quick response!
