### ISSUE TITLE
Webpack & Uglify.js build problem

### ISSUE THREAD

**Issue by mbertrand** [streamroot/videojs5-hlsjs-source-handler#44]
When attempting to build a distribution that includes videojs5-hlsjs-source-handler with Webpack, Babel and Uglify, the following exception occurs:

```
ERROR in video-c9d821f60adba8a625ac.js from UglifyJs
Unexpected token: name (QualityMenuItem) [./~/videojs-quality-picker/lib/quality-menu-item.js:3,0][video-c9d821f60adba8a625ac.js:36836,6]
```

**Comment by dylanjha** [comment]
@mbertrand I got this same issue, what did you do to resolve this?

**Comment by mbertrand** [comment]
@dylanjha I ended up [switching to `videojs-contrib-hls`](https://github.com/mitodl/odl-video-service/blob/eb15c51481e2fd7c8f5f85f9fdd0ad5753cd87e8/package.json#L94) instead:

- [webpack config alias](https://github.com/mitodl/odl-video-service/blob/eb15c51481e2fd7c8f5f85f9fdd0ad5753cd87e8/webpack.config.shared.js#L31)

**Comment by tri170391** [comment]
It is caused by the outdated quality picker plugin, I have just updated to remove it. Meanwhile you can still include it as a separate plugin.

**Comment by ruslandinov** [comment]
Problem seems to be solved, closing. 
Ping me if you still have this issue.
