### ISSUE TITLE
the hls.js version in package.json should be update.

### ISSUE THREAD

**Issue by pspgbhu** [streamroot/videojs5-hlsjs-source-handler#55]
Now the latest version of hls.js is v0.8.9, but this package is dependent on hls.js v0.6.21.

hls.js v0.6.21 not work well with android 4.4, so it need update to version v0.8.9 to fix it.

**Comment by tri170391** [comment]
I have just synced this repo with the latest production code.

**Comment by pspgbhu** [comment]
@tri170391  you are so efficient!
