### ISSUE TITLE
Error 'Maximum call stack size exceeded' when i called player.src('xxx')

### ISSUE THREAD

**Issue by pspgbhu** [streamroot/videojs5-hlsjs-source-handler#57]
Browser: Chrome 64.0.3282.186

It is ease to occur, just call:
```
player.src('https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8')
```
or call:
```
player.dispose();
```

And you cloud reshow this bug in the example of master branch.

**Comment by tri170391** [comment]
Smells like an error I get when updating `webpack.config`. Have you try rebuilding the dist. I'll check if I forgot to commit the correct dist.

**Comment by pspgbhu** [comment]
I had try to rebuild the dist. It is not work. And I exec `npm run dev` in the example, browsing `http://localhost:8080/example/index.html`, the error still occurred.

**Comment by tri170391** [comment]
I'll investigate this when I have access to my work PC.

**Comment by tri170391** [comment]
This PR should fix your issue https://github.com/streamroot/videojs5-hlsjs-source-handler/pull/58

Nice catch 😉

**Comment by pspgbhu** [comment]
Thanks, it work!
